## Dot product example (nut butter sales)

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [3]:
# Create weekly_sales DataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], columns=["Almond butter", "Peanut butter", "Shea butter"])
weekly_sales

Almond butter  Peanut butter  Shea butter
Mon               12             15            0
Tues               3              3            7
Wed                9             19           18
Thurs              4              6           12
Fri                1              6            7

In [4]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [5]:
# Create butter prices Dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Shea butter"])
butter_prices

Almond butter  Peanut butter  Shea butter
Price             10              8           12

In [6]:
# Will produce an error. It is intentional
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [7]:
# Transpose sales_amounts++
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [8]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [9]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [10]:
# Will produce an error. It is intentional
weekly_sales["Total ($)"] = daily_sales
weekly_sales

ValueError: Cannot set a DataFrame with multiple columns to the single column Total ($)

In [11]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Shea butter  Total ($)
Mon               12             15            0        240
Tues               3              3            7        138
Wed                9             19           18        458
Thurs              4              6           12        232
Fri                1              6            7        142

### Comparison Operators

In [13]:
a1 = np.array([1,2,3])
a1.shape

(3,)

In [15]:
a2 = np.random.randint(low=2, high=8, size=(3))
a2

array([3, 7, 2])

In [16]:
a1 > a2

array([False, False,  True])

In [17]:
bool_array = a2 >= a1
bool_array

array([ True,  True, False])

In [19]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

### Sorting arrays


In [20]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[9, 4, 3, 0, 3],
       [5, 0, 2, 3, 8],
       [1, 3, 3, 3, 7]])

In [21]:
random_array.shape

(3, 5)

In [22]:
np.sort(random_array)

array([[0, 3, 3, 4, 9],
       [0, 2, 3, 5, 8],
       [1, 3, 3, 3, 7]])

In [23]:
np.argsort(random_array)

array([[3, 2, 4, 1, 0],
       [1, 2, 3, 0, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [24]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [25]:
np.argmax(a1)

2

In [26]:
np.argmin(a2)

2

In [27]:
np.argmax(random_array, axis=0)

array([0, 0, 0, 1, 1], dtype=int64)

In [28]:
np.argmax(random_array, axis=1)

array([0, 4, 4], dtype=int64)

## Practical Examples

<img src='images/panda.png' />

In [30]:
# Turn an image into a Numpy array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))



Matplotlib is building the font cache; this may take a moment.


<class 'numpy.ndarray'>


In [32]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src="images/car-photo.png"/>

In [33]:
car = imread("images/car-photo.png")
car.shape, car.ndim, car.size

((431, 575, 4), 3, 991300)

<img src="images/dog-photo.png"/>

In [34]:
dog = imread("images/dog-photo.png")
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274