## Dot product example (nut butter sales)

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [3]:
# Create weekly_sales DataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], columns=["Almond butter", "Peanut butter", "Shea butter"])
weekly_sales

Almond butter  Peanut butter  Shea butter
Mon               12             15            0
Tues               3              3            7
Wed                9             19           18
Thurs              4              6           12
Fri                1              6            7

In [4]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [6]:
# Create butter prices Dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Shea butter"])
butter_prices

Almond butter  Peanut butter  Shea butter
Price             10              8           12

In [7]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [9]:
# Transpose sales_amounts++
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])