# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr_1 = np.array([2,3,5])



# Create a 2-dimensional NumPy array using np.array()
arr_2 = np.array([[2,4,6],[1,3,5]])



# Create a 3-dimensional Numpy array using np.array()
arr_3 =np.array([[5,10,15],[3,6,9], [7,14,21]])

arr_1, arr_2, arr_3


(array([2, 3, 5]),
 array([[2, 4, 6],
        [1, 3, 5]]),
 array([[ 5, 10, 15],
        [ 3,  6,  9],
        [ 7, 14, 21]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr_1.shape, arr_1.ndim, type(arr_1), arr_1.size, arr_1.dtype


((3,), 1, numpy.ndarray, 3, dtype('int32'))

In [4]:
# Attributes of 2-dimensional array
arr_2.shape, arr_2.ndim, arr_2.size, arr_2.dtype, type(arr_2)


((2, 3), 2, 6, dtype('int32'), numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
arr_3.shape, arr_3.ndim, type(arr_3), arr_3.size, arr_3.dtype


((3, 3), 2, numpy.ndarray, 9, dtype('int32'))

In [6]:
arr_3

array([[ 5, 10, 15],
       [ 3,  6,  9],
       [ 7, 14, 21]])

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
arr_3_df = pd.DataFrame(arr_3, index=['Monday','Tuesday', 'Wednesday'], columns=['Dog', 'Cat', 'Sheep'])
arr_3_df

Dog  Cat  Sheep
Monday       5   10     15
Tuesday      3    6      9
Wednesday    7   14     21

In [8]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones(shape=(10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes_array = np.zeros(shape=(7,2,3))
zeroes_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,10, size=(7,2))
random_array


array([[3, 5],
       [6, 9],
       [6, 5],
       [9, 9],
       [1, 7],
       [1, 0],
       [0, 3]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.04983307, 0.21040507, 0.71336926, 0.83481587, 0.920941  ],
       [0.98388246, 0.75615912, 0.83379001, 0.80746341, 0.65382557],
       [0.41037234, 0.15160048, 0.21376758, 0.60548923, 0.9538854 ]])

In [55]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
step_array = np.random.randint(0,10, size=(4,6))
step_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [57]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
r_array = np.random.randint(1,10, size=(3,7))


# Find the unique numbers in the array you just created
np.unique(r_array)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# Find the 0'th index of the latest array you created
r_array[0]


array([7, 8, 3, 1, 4, 2, 8])

In [61]:
# Get the first 2 rows of latest array you created
r_array[:2]



array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [62]:
# Get the first 2 values of the first 2 rows of the latest array
r_array[:2, :2]


array([[7, 8],
       [4, 2]])

In [64]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_arr = np.random.randint(10, size=(3,5))
ones = np.ones((3,5))

In [65]:
# Add the two arrays together
random_arr + ones

array([[ 1.,  8.,  3.,  3.,  1.],
       [ 5., 10.,  7., 10.,  9.],
       [ 7.,  9.,  8.,  2.,  1.]])

In [67]:
# Create another array of ones of shape (5, 3)
ones_two = np.ones((5,3))

In [69]:
# Try add the array of ones and the other most recent array together
random_arr + ones_two.T

array([[ 1.,  8.,  3.,  3.,  1.],
       [ 5., 10.,  7., 10.,  9.],
       [ 7.,  9.,  8.,  2.,  1.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [71]:
# Create another array of ones of shape (3, 5)
arr_4 = np.ones((3,5))


In [72]:
# Subtract the new array of ones from the other most recent array
random_arr-arr_4

array([[-1.,  6.,  1.,  1., -1.],
       [ 3.,  8.,  5.,  8.,  7.],
       [ 5.,  7.,  6.,  0., -1.]])

In [73]:
# Multiply the ones array with the latest array
random_arr * arr_4


array([[0., 7., 2., 2., 0.],
       [4., 9., 6., 9., 8.],
       [6., 8., 7., 1., 0.]])

In [75]:
# Take the latest array to the power of 2 using '**'
random_arr**2

array([[ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64],
       [36, 64, 49,  1,  0]])

In [76]:
# Do the same thing with np.square()
np.square(random_arr)


array([[ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64],
       [36, 64, 49,  1,  0]])

In [77]:
# Find the mean of the latest array using np.mean()
np.mean(random_arr)


4.6

In [78]:
# Find the maximum of the latest array using np.max()
np.max(random_arr)

9

In [79]:
# Find the minimum of the latest array using np.min()
np.min(random_arr)

0

In [80]:
# Find the standard deviation of the latest array
np.std(random_arr)

3.3426536364591137

In [81]:
# Find the variance of the latest array
np.var(random_arr)


11.173333333333336

In [82]:
# Reshape the latest array to (3, 5, 1)
random_arr.reshape(3,5,1)


array([[[0],
        [7],
        [2],
        [2],
        [0]],

       [[4],
        [9],
        [6],
        [9],
        [8]],

       [[6],
        [8],
        [7],
        [1],
        [0]]])

In [83]:
# Transpose the latest array
random_arr.T

array([[0, 4, 6],
       [7, 9, 8],
       [2, 6, 7],
       [2, 9, 1],
       [0, 8, 0]])

What does the transpose do?

In [84]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

first_arr = np.random.randint(10, size=(3,3))
second_arr = np.random.randint(10, size=(3,2))


In [85]:
# Perform a dot product on the two newest arrays you created
first_arr.dot(second_arr)


array([[52, 87],
       [40, 79],
       [14, 20]])

In [86]:
np.dot(first_arr, second_arr)

array([[52, 87],
       [40, 79],
       [14, 20]])

In [87]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_1 = np.random.randint(10, size=(4,3))
arr_2 = np.random.randint(10, size=(4,3))

In [88]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_1, arr_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [89]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr_1, arr_2.T)


array([[102,  50, 134, 120],
       [ 93,  65, 161,  90],
       [ 54,  15,  66,  57],
       [ 66,  32,  83,  81]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [90]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_1 = np.random.randint(10, size=(2,1))
arr_2 = np.random.randint(10, size=(2,1))

In [91]:
# Compare the two arrays with '>'
arr_1 > arr_2

array([[False],
       [ True]])

What happens when you compare the arrays with `>`?

In [92]:
# Compare the two arrays with '>='
arr_2 >= arr_1


array([[ True],
       [False]])

In [93]:
# Find which elements of the first array are greater than 7
arr_1 > 7

array([[False],
       [ True]])

In [94]:
# Which parts of each array are equal? (try using '==')
arr_1 == arr_2


array([[ True],
       [False]])

In [95]:
# Sort one of the arrays you just created in ascending order
np.sort(arr_2)

array([[6],
       [0]])

In [96]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr_4)


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [101]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_arr)

6

In [100]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_arr)

0

In [102]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_arr, axis=1)

array([1, 1, 1], dtype=int64)

In [103]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_arr, axis=0)

array([0, 0, 0, 2, 0], dtype=int64)

In [106]:
# Create an array of normally distributed random numbers
np.random.randn(4,5)

array([[ 0.91488432, -0.66606062, -0.51378749,  0.3013228 , -1.45851692],
       [-0.66273831, -0.14647281, -0.84601702, -0.82248937,  1.08672702],
       [ 1.00498688, -0.44176602, -0.08416509,  1.23701607, -1.42647888],
       [ 0.33802266,  1.9745712 ,  1.96503476, -1.93991122, -0.76262696]])

In [107]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100, 10)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.